version: "3"

services:
  #frontend
  website:
    build:
      context: .
      dockerfile: website_dockerfile
    stdin_open: true
    tty: true
    ports:
      - "5050:5050"
    volumes:
      - ./datasets:/app/datasets/

  #backend
  clean:
    build:
      context: .
      dockerfile: clean_dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./datasets:/app/datasets/
    restart: always
  
  db_data:
    build: 
      context: .
      dockerfile: db_data_dockerfile
    ports:
      - "3308:3306"
    volumes:
      - ./datasets:/app/datasets/
    restart: always
  
  predict:
    build:
      context: .
      dockerfile: predict_dockerfile
    stdin_open: true
    tty: true
    ports:
      - "5000:3306"
    volumes:
      - ./datasets:/app/datasets/
    restart: always

  #agent based simulation model
  netlogo:
    build:
      context: .
      dockerfile: simulation_model_dockerfile
      args:
        NETLOGO_VERSION: 6.3.0
    container_name: netlogo
    volumes_from:
      - x11-bridge
    volumes:
      - ./datasets:/home/datasets/

  x11-bridge:
    image: jare/x11-bridge
    container_name: x11-bridge
    environment:
      - MODE=tcp
      - XPRA_HTML=yes
      - DISPLAY=:14
      - XPRA_PASSWORD=111
    ports:
      - "10000:10000"